language: cpp
sudo: required
dist: xenial
compiler:
- gcc
# - clang  # Don't compile in clang until openmp errors can be resolved
before_install:
- sudo apt-get install cpputest doxygen graphviz latexmk pandoc texlive-latex-extra texlive-fonts-recommended
script:
- cd $TRAVIS_BUILD_DIR
- autoconf
- ./configure
- make
- make docs
- make test
- make dist
- test/runtests
notifications:
  slack: iu-hpc-users:7OKYnBwu5Cuss5ja7GcwxsLQ
